### ISSUE TITLE
Sanity checking on preliminary MEDS

### ISSUE THREAD

**Issue by seccolf** [seccolf/mcal_sim_test#5]
Things to check on existing MEDS files. Start with the simplest ones in the list below. 

on the MEDS themselves:
- [x] eyeball bmasks, PSFs, weigths, galaxy images
- [ ] check that PSFs are centered on stamps
- [ ] see if images are actually messed up in pixels/cutouts where bmasks are set to something not good (>0)
- [ ] see if galaxies that are on the edge of chips are properly masked

after running metacal on the files:
- [ ] look for outliers in S/N, T/T_PSF, e1, e2 and how many objects get cut with bounds like  10<S/N<100 and T/T_PSF>~1.
- [ ] look at mean shear <e1> and <e2> (nonzero expected for <e1>)
- [ ] look at mean shear as a function of PSF size (original PSF size, not reconstructed)

Some plots to follow are Figs.  4, 7 and 10 in Gatti el al https://arxiv.org/pdf/2011.03408.pdf (Y3 shear catalog)

**Comment by seccolf** [comment]
@chihway posted images in https://www.dropbox.com/sh/sfpyxke6x77g9zr/AAASgTKd7HNl9I6c59dGb1HIa?dl=0

**Comment by DhayaaAnbajagane** [comment]
Closing because tasks now being handled in [shearcat repository](https://github.com/seccolf/shearcat)
