### ISSUE TITLE
Get rho stats

### ISSUE THREAD

**Issue by seccolf** [seccolf/mcal_sim_test#7]
We need to characterize PSF residuals by computing rho statistics (eqs. 3.4-3.8 in the [Y1 catalog paper](https://arxiv.org/pdf/1708.01533.pdf) among other references). In order to do that, follow roughly the steps below. (Also see threads [here](https://delve-survey.slack.com/archives/C027UBKTJPL/p1646838569761859) and [here](https://delve-survey.slack.com/archives/C027UBKTJPL/p1647018722067569))

- [x] get a list of all final cut images and their psfex solutions and star lists

Finalcut images are [here](https://decade.ncsa.illinois.edu/deca_archive/DEC/finalcut/) and processing files are organized by exposure number, CCD number and etc. The PSF model files are also in there. The way to get the correct paths to the relevant files via easyaccess queries is shown in [this notebook](https://github.com/seccolf/mcal_sim_test/blob/32fd19bbb15bcbec013f67cd99bcfdb802d94cd4/notebooks/example_queries.ipynb). PSFex solutions are files ending in `*.psf` and stars are in `*starlist*` files 

- [x] For each entry above, download the data

Downloaded examples to test code with. Full run will need to be done on actual server locally.

- [x] then make a postage stamp around each star used by psfex

Follow [this notebook](https://github.com/seccolf/mcal_sim_test/blob/32fd19bbb15bcbec013f67cd99bcfdb802d94cd4/notebooks/plot_star_cutouts.ipynb)

- [ ] measure the moments and size of the real star and its model

- [ ] write the data to a binary fits table with scalar columns

**Comment by DhayaaAnbajagane** [comment]
Closing because these tasks are now being handled/logged in [shearcat repository](https://github.com/seccolf/shearcat)
